# encrypt_addr.py — AES-256-GCM encrypt relay + worker secrets
# Generates opaque flat-blob header to frustrate static analysis.
# Output: src/multiplayer/encrypted_addr_local.h (.gitignored)

import os, sys
try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("Error: need 'pip install cryptography'")
    sys.exit(1)

SECRETS = [
    (b"tcp://8.218.97.97:11010", "Relay"),
    (b"8.218.",                  "Relay"),
    (b"https://beta-auth-scllhxgtcn.cn-shenzhen.fcapp.run", "Worker"),
]

def hexdump(data):
    return ", ".join(f"0x{b:02x}" for b in data)

# Encrypt
keys = {}
salts = {}
entries_by_ns = {}
for plaintext, ns in SECRETS:
    if ns not in keys:
        keys[ns] = AESGCM.generate_key(256)
        salts[ns] = os.urandom(8)
        entries_by_ns[ns] = []
    entries_by_ns[ns].append(plaintext)

encrypted = {}  # ns -> [(nonce, ct, tag), ...]
for ns, plaintexts in entries_by_ns.items():
    key = keys[ns]
    salt = salts[ns]
    final_key = bytes(a ^ b for a, b in zip(key, salt * 4))
    encrypted[ns] = []
    for plaintext in plaintexts:
        nonce = os.urandom(12)
        aes = AESGCM(final_key)
        ct_with_tag = aes.encrypt(nonce, plaintext, None)
        tag = ct_with_tag[-16:]
        ct = ct_with_tag[:-16]
        encrypted[ns].append((nonce, ct, tag))
    print(f"[{ns}] encrypted {sum(len(p) for p in plaintexts)}B")

# Build flat blob: [Relay: salt(8)+key(32)+nonce(12)+ct(len1)+tag(16)+
#                           nonce2(12)+ct2(len2)+tag2(16)]
#                 [Worker: salt(8)+key(32)+nonce(12)+ct(len3)+tag(16)]
r_salt, r_key = salts["Relay"], keys["Relay"]
r_nonce1, r_ct1, r_tag1 = encrypted["Relay"][0]
r_nonce2, r_ct2, r_tag2 = encrypted["Relay"][1]
w_salt, w_key = salts["Worker"], keys["Worker"]
w_nonce, w_ct, w_tag = encrypted["Worker"][0]

blob_parts = [
    r_salt, r_key, r_nonce1, r_ct1, r_tag1,
    r_nonce2, r_ct2, r_tag2,
    w_salt, w_key, w_nonce, w_ct, w_tag,
]
blob = b"".join(blob_parts)

# Compute layout
O = 0
LAYOUT = {}
for name, part in [
    ("kRelaySalt", r_salt),
    ("kRelayKey", r_key),
    ("kRelayNonce", r_nonce1),
    ("kRelayCT", r_ct1),
    ("kRelayTag", r_tag1),
    ("kRelayPrefixNonce", r_nonce2),
    ("kRelayPrefixCT", r_ct2),
    ("kRelayPrefixTag", r_tag2),
    ("kWorkerSalt", w_salt),
    ("kWorkerKey", w_key),
    ("kWorkerNonce", w_nonce),
    ("kWorkerCT", w_ct),
    ("kWorkerTag", w_tag),
]:
    LAYOUT[name] = (O, len(part))
    O += len(part)

# Write output
script_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(script_dir, "..", "src", "multiplayer", "encrypted_addr_local.h")
os.makedirs(os.path.dirname(out_path), exist_ok=True)

def offset_name(name):
    return name  # keep plain kRelaySaltOff etc.

with open(out_path, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/encrypt_addr.py — DO NOT EDIT\n")
    f.write("// .gitignored — keep local.\n")
    f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
    f.write(f"constexpr uint8_t  kBlob[{len(blob)}] = {{ {hexdump(blob)} }};\n\n")

    for name, (offs, sz) in LAYOUT.items():
        o_name = offset_name(name)
        f.write(f"constexpr size_t  {o_name}Off = {offs};\n")
        f.write(f"constexpr size_t  {o_name}Len = {sz};\n")
    f.write("\n")

print(f"\nWritten: {out_path} ({len(blob)} bytes total)")
print("Done. Keep this file local.")
